MyProject/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyProject.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyProject.Controllers.Components
{
    public class PagerViewComponent : ViewComponent
    {

        public Task<IViewComponentResult> InvokeAsync(PaingBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

MyProject/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyProject.Application.ModelRequestService.ServiceRequest.Product;
using MyProject.Common;
using MyProject.Service;

namespace MyProject.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApi _productApi;
        public ProductController(IProductApi productApi)
        {
            _productApi = productApi;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string keyword, int pageIndex = 1, int pageSize = 2)
        {
            var search = new SearchingBase()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize
            };
            var result = await _productApi.GetAllPaging(search);
            
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(ProductCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                TempData["result"] = "Thêm sản phẩm thất bại !";
                return RedirectToAction("Index","Product");
            }
            var result = await _productApi.CreateProduct(request);
            if (result.Successed)
            {
                TempData["result"] = "Thêm sản phẩm thành công !";
                return RedirectToAction("Index", "Product");
            }
            TempData["result"] = "Thêm sản phẩm thất bại !";
            return RedirectToAction("Index", "Product");
        }

        [HttpGet]
        public async Task<JsonResult> GetProduct(int id)
        {
            var result = await _productApi.GetProduct(id);
            return Json(result);
        }
        
    }
}

MyProject/Views/Product/Index.cshtml
@using MyProject.Common;
@model Pagination<MyProject.Data.Entities.Product>
@{
    ViewData["Title"] = "Quản lý sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (ViewBag.SuccessMsg != null)
    {
        <div id="msgAlert" class="alert alert-success" style="position:absolute;" role="alert">
            @ViewBag.SuccessMsg
        </div>
    }
<div class="container-fluid">
    <h1 class="mt-4">Danh sách người dùng</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Người dùng</a></li>
        <li class="breadcrumb-item active">Danh sách</li>
    </ol>

    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table mr-1"></i>
            Người dùng
            <button class="btn btn-success float-right" id="create-product">
                <i class="fas fa-plus-circle"></i>
                Thêm mới
            </button>

        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>

                            <th>Hình ảnh</th>
                            <th>Tên SP</th>
                            <th>Thương hiệu</th>
                            <th>Mô tả</th>
                            <th>Tùy chọn</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model.Data)
                        {
                        <tr>
                            <td>
                                <img src="https://localhost:5001/user-content/@(item.ProductImages.FirstOrDefault() !=null?item.ProductImages.FirstOrDefault().ImagePath:"")" style="width:120px;height:90px;" />

                            </td>
                            <td>@item.Name</td>
                            <td>@item.Brand.Name</td>
                            <td>@item.Description</td>

                            <td >
                                <button type="button" data-id="@item.Id" class="btn btn-sm btn-success update-product" style="margin-right:5px;">Sửa</button>
                                <button type="button" data-id="@item.Id" class="btn btn-sm btn-danger delete-product">Xóa</button>
                            </td>
                        </tr>
                        }


                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", new PaingBase() { CurrentPage = Model.CurrentPage, PageSize = Model.PageSize, TotalRows = Model.TotalRows })
        </div>
    </div>
</div>

@*modal update*@

<div class="modal fade" id="modal-create" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Tạo mới sản phẩm</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form method="post" asp-action="CreateProduct" asp-controller="Product" enctype="multipart/form-data">
                <div class="modal-body">

                    <div class="row">
                        <div class="col-md-1 col-sm-1"></div>
                        <div class="col-md-10 col-sm-10">
                            <div class="x_panel">
                                <div class="x_content">
                                    @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
                                    <div class="field item form-group">
                                        <input type="hidden" name="id" id="id" />
                                        <input type="hidden" name="UserCreated" id="UserCreated" value="@User.Identity.Name" />

                                        <label class="col-form-label col-md-3 col-sm-3  label-align">
                                            Tên sản phẩm :<span class="required">*</span>

                                        </label>
                                        <div class="col-md-8 col-sm-8">

                                            <input type="text" class="form-control" maxlength="100" name="Name" id="name"
                                                   required="required" />
                                        </div>
                                    </div>
                                    <div class="field item form-group">
                                        <label class="col-form-label col-md-3 col-sm-3  label-align">
                                            Thương hiệu :<span class="required">*</span>
                                        </label>
                                        <div class="col-md-8 col-sm-8">
                                            <select name="BrandId" id="brand-id" class="form-control">
                                                <option>Adidas</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="field item form-group">
                                        <label class="col-form-label col-md-3 col-sm-3  label-align">
                                            Mô tả sản phẩm :<span class="required">*</span>
                                        </label>
                                        <div class="col-md-8 col-sm-8">
                                            <textarea name="Description" id="description" class="form-control"></textarea>
                                        </div>
                                    </div>
                                    <div class="field item form-group">
                                        <label class="col-form-label col-md-5 col-sm-5  label-align">
                                            Giới thiệu sản phẩm :<span class="required">*</span>
                                        </label>
                                        <div class="col-md-8 col-sm-8">
                                            <textarea name="Details" id="details"class="form-control"></textarea>
                                        </div>
                                    </div>

                                    <div class="field item form-group">
                                        <label class="col-form-label col-md-3 col-sm-3  label-align">
                                            Hình ảnh : <span class="required">*</span>
                                        </label>
                                        <div class="col-md-8 col-sm-8">
                                            <input multiple type="file" class="form-control-file" name="ImageProduct" id="image"/>
                                        </div>
                                    </div>
                                    <div class="field item form-group">
                                        <label class="col-form-label col-md-3 col-sm-3  label-align">
                                            Tình trạng : <span class="required">*</span>
                                        </label>
                                        <div class="col-md-8 col-sm-8">
                                            <select name="Status" id="status" class="form-control">
                                                <option value="true">Kích hoạt</option>
                                                <option value="false">Không kích hoạt</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                    <button type='reset' class="btn btn-info">Reset</button>
                    <button type="submit" class="btn btn-success">Lưu lại</button>
                </div>

            </form>
        </div>
    </div>
</div>

@*end modal update*@

@*modal delete*@


<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Bạn có chắc chắn muốn xóa ?</h2>
            </div>
            <div class="modal-body">
                Khi ấn xác nhận sẽ xóa người dùng
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy bỏ</button>
                <form method="post" asp-controller="User" asp-action="Delete">
                    <input type="hidden" id="id-delete" name="id" />
                    <button type="submit" class="btn btn-danger btn-ok">Xác nhận</button>
                </form>

            </div>
        </div>
    </div>
</div>
@*end modal delete*@

@section js
{

    <script src="~/js/product.js"></script>
}